{{- if and .Values.ingress.enabled .Values.radarr.enabled .Values.radarr.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "media-server.fullname" . }}-radarr
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: radarr
  annotations:
    {{- if .Values.ingress.tls.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certManager.issuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.radarr.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.radarr.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.radarr.ingress.hostname }}
    secretName: {{ include "media-server.tlsSecretName" .Values.radarr.ingress }}
  {{- end }}
  rules:
  - host: {{ .Values.radarr.ingress.hostname }}
    http:
      paths:
      - path: {{ .Values.radarr.ingress.path }}
        pathType: {{ .Values.radarr.ingress.pathType }}
        backend:
          service:
            name: {{ include "media-server.fullname" . }}-radarr
            port:
              number: {{ .Values.radarr.service.port }}
{{- end }}
