apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-app-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/example-argocd.git
    targetRevision: HEAD
    path: environments/prod/deployments/echo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
