cert-manager:
  installCRDs: true
  
  global:
    leaderElection:
      namespace: cert-manager
  
  replicaCount: 2
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  
  webhook:
    replicaCount: 2
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
  
  cainjector:
    replicaCount: 2
    resources:
      requests:
        cpu: 25m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
        
  # Production cluster issuer will be created separately
  # This is just the cert-manager installation
