apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app
  namespace: echo-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-dev"
spec:
  ingressClassName: nginx
  rules:
  - host: echo.dev.786999.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo-app
            port:
              number: 80
  tls:
    - hosts:
      - echo.dev.786999.xyz
      secretName: echo-app-tls
    
