{{- if and (eq .Values.storage.type "pvc") .Values.storage.pvc.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
  labels:
    {{- include "media-server.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.storage.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
  {{- if .Values.storage.pvc.storageClass }}
  storageClassName: {{ .Values.storage.pvc.storageClass }}
  {{- end }}
{{- end }}
