apiVersion: v2
name: nginx-ingress
description: Nginx Ingress Controller
type: application
version: 1.0.0
appVersion: "1.11.2"

dependencies:
  - name: ingress-nginx
    version: 4.11.2
    repository: https://kubernetes.github.io/ingress-nginx
