ingress-nginx:
  controller:
    replicaCount: 1
    
    service:
      type: LoadBalancer
      # For development, you might want NodePort instead
      # type: NodePort
    
    resources:
      requests:
        cpu: 100m
        memory: 90Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
    admissionWebhooks:
      enabled: false

