apiVersion: v2
name: cert-manager
description: Certificate management for Kubernetes
type: application
version: 1.0.0
appVersion: "1.15.3"

dependencies:
  - name: cert-manager
    version: 1.15.3
    repository: https://charts.jetstack.io
