apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: json-keys-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: json-keys-secret
    creationPolicy: Owner
  data:
  - secretKey: CF_API_TOKEN
    remoteRef:
      key: CF_JSON_SECRET
      property: CF_API_TOKEN
  - secretKey: CF_API_EMAIL
    remoteRef:
      key: CF_JSON_SECRET
      property: CF_API_EMAIL
  - secretKey: CF_ZONE_ID
    remoteRef:
      key: CF_JSON_SECRET
      property: CF_ZONE_ID
