apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: json-extract-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: json-extract-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: CF_JSON_SECRET

