# External DNS configuration for dev environment
provider:
  name: cloudflare
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns-credentials
          key: CF_API_TOKEN

# Domains that ExternalDNS will manage
domainFilters:
  - 786999.xyz

# Sources to watch for DNS records
sources:
  - service
  - ingress

# Policy for managing DNS records
policy: upsert-only

# Registry for tracking ownership
registry: txt
txtOwnerId: external-dns-dev

# Cloudflare specific settings
cloudflare:
  proxied: false
