# Default values for external-dns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Provider configuration
provider: cloudflare

# Cloudflare configuration
cloudflare:
  proxied: false  # Set to true if you want to use Cloudflare's proxy
  apiTokenSecretRef:  # Reference to the secret containing Cloudflare API token
    name: external-dns-credentials
    key: CF_API_TOKEN

# Domain filters - specify the domains you want to manage
domainFilters:
  - "786999.xyz"
  - "dev.ithut.net"

# Sources to watch for DNS records
sources:
  - service
  - ingress
  - ingress-class
  - crd

# Policy for managing DNS records
policy: upsert-only

# Registry configuration (how ExternalDNS tracks ownership)
registry: txt

txtOwnerId: external-dns

txtPrefix: external-dns-  # Prefix for TXT records

# Log level
logLevel: debug  # Temporarily set to debug for troubleshooting

# Deployment configuration
replicaCount: 1

image:
  repository: registry.k8s.io/external-dns/external-dns
  pullPolicy: IfNotPresent
  
  # Resource limits
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 50Mi
  
  # Security context
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534
    capabilities:
      drop:
        - ALL
  
  # Service account
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  
  # RBAC
  rbac:
    create: true
  
  # Logging
  logLevel: info
  logFormat: text
  
  # Sync policy
  policy: upsert-only  # Options: sync, upsert-only
  
  # Registry for storing DNS records state
  registry: txt
  txtOwnerId: "external-dns-dev"
  
  # Interval between DNS updates
  interval: 1m
  
  # Trigger loop on events in addition to interval
  triggerLoopOnEvent: false
  
  # Metrics
  metrics:
    enabled: true
    port: 7979
  
  # Extra environment variables (for provider-specific config)
  env:
    # Cloudflare configuration using API token
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns-credentials
          key: CF_API_TOKEN
