external-dns:
  provider:
    name: cloudflare

  txtOwnerId: k8s-dev-cluster-proxmox-server
  policy: upsert-only
  
  extraArgs:
    annotation-filter: "external-dns.alpha.kubernetes.io/hostname"
    ingress-hostname-source: "annotation-only"

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns-credentials
          key: CF_API_TOKEN