external-dns:
  provider:
    name: cloudflare
  registry: "noop"
  txtOwnerId: k8s-dev-cluster-proxmox-server
  policy: upsert-only
  # logLevel: debug
  extraArgs:
    annotation-filter: "external-dns.alpha.kubernetes.io/hostname"   
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns-credentials
          key: CF_API_TOKEN