external-dns:
  provider:
    name: cloudflare

  txtOwnerId: k8s-dev-cluster
  policy: sync

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns-credentials
          key: CF_API_TOKEN