argo-cd:
  configs:
    params:
      server.insecure: true
    cm:
      application.instanceLabelKey: argocd.argoproj.io/instance
    
  server:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.dev.786999.xyz
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
        # External DNS annotations
        external-dns.alpha.kubernetes.io/hostname: "argocd.dev.786999.xyz"
        external-dns.alpha.kubernetes.io/ttl: "60"
        external-dns.alpha.kubernetes.io/ip-address: "51.89.191.218"
      tls: true
      
  controller:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
  repoServer:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    
  applicationSet:
    enabled: true
    
  notifications:
    enabled: false
    
  dex:
    enabled: false
