apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/example-argocd.git
    targetRevision: HEAD
    path: environments/prod/charts/nginx-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
