apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: external-dns-credentials
    creationPolicy: Owner
  data:
  - secretKey: CLOUDFLARE_API_KEY
    remoteRef:
      key: "CF_786_API_KEY"
