apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    reconcile.external-secrets.io/force: "true"
  labels:
    app.kubernetes.io/managed-by: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: external-dns-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: CF_API_TOKEN
    remoteRef:
      key: "CF_786_API_KEY"
      conversionStrategy: Default
      decodingStrategy: None  # Using the existing API token from Bitwarden
