apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      # Bitwarden EU API URLs
      apiURL: https://vault.bitwarden.eu/api
      identityURL: https://vault.bitwarden.eu/identity
      
      # Authentication using machine account token
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets-system
      
      # Bitwarden SDK Server URL with TLS
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets-system.svc.cluster.local:9998
      
      # CA Bundle from the generated certificate
      caProvider:
        type: "Secret"
        name: "bitwarden-sdk-server-tls"
        namespace: "external-secrets-system"
        key: "ca.crt"
      
      # Your Bitwarden organization and project IDs
      organizationID: "ee359e08-791d-4494-a1d8-b34600a84073"
      projectID: "919e41f2-f612-437c-9d90-b34600a98a81"
