apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/example-argocd.git
    targetRevision: HEAD
    path: environments/dev/charts/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
