apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    reconcile.external-secrets.io/force: "true"
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-dev
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: grafana-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: GRAFANA
