apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secret-test-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/example-argocd.git
    targetRevision: HEAD
    path: environments/dev/deployments/external-secret-test
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secret-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3
