apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: media-server
    app.kubernetes.io/part-of: media-stack
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/zeeemughal/example-argocd.git
    targetRevision: testing
    path: environments/dev/charts/media-server
    helm:
      releaseName: media-server
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: media-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/resources/requests/storage
