{{- if eq .Values.config.advertisementMode "bgp" }}
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default-bgpadvertisement
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  {{- range .Values.config.addressPools }}
  {{- if .enabled }}
  - {{ .name }}
  {{- end }}
  {{- end }}
{{- end }}
