{{- range .Values.config.addressPools }}
{{- if .enabled }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  addresses:
  {{- range .addresses }}
  - {{ . }}
  {{- end }}
  {{- if hasKey . "autoAssign" }}
  autoAssign: {{ .autoAssign }}
  {{- end }}
  {{- if hasKey . "avoidBuggyIPs" }}
  avoidBuggyIPs: {{ .avoidBuggyIPs }}
  {{- end }}
{{- end }}
{{- end }}
