apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-secrets
  namespace: cloudflare-tunnel-ingress-controller
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    reconcile.external-secrets.io/force: "true"
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
    app.kubernetes.io/instance: cloudflare-tunnel-dev
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cloudflare-tunnel-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: CF_INGRESS_TOKEN
      property: .
  - secretKey: CLOUDFLARE_ACCOUNT_ID
    remoteRef:
      key: CF_ACCOUNT_ID
      property: .
  - secretKey: CLOUDFLARE_TUNNEL_NAME
    remoteRef:
      key: CF_TUNNEL_NAME_MYK3S
      property: .