apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Infrastructure applications (Wave 1)
  - charts/cert-manager/pipeline/application.yaml
  - charts/nginx-ingress/pipeline/application.yaml
  - charts/cluster-issuer/pipeline/application.yaml
  - charts/external-secrets/pipeline/application.yaml
  #- charts/external-dns/pipeline/application.yaml
  - charts/cloudflare-tunnel-ingress-controller/pipeline/application.yaml
  
  # ArgoCD self-management (Wave 2)
  - charts/argocd/pipeline/application.yaml
  
  # Application deployments (Wave 3+)
  - deployments/echo-app/pipeline/application.yaml
  
  # Main pipeline self-reference
  - main-pipeline-app.yaml

labels:
  - pairs:
      environment: dev
      managed-by: argocd

patches:
  - target:
      kind: Application
      group: argoproj.io
      version: v1alpha1
    patch: |-
      - op: add
        path: /spec/syncPolicy/retry
        value:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      - op: replace
        path: /spec/source/targetRevision
        value: testing
